name:                ParserStuff
version:             0.1.0.0
github:              "githubuser/ParserStuff"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on GitHub at <https://github.com/githubuser/ParserStuff#readme>

dependencies:
- base >= 4.7 && < 5
- HTF
- parsec
- text

library:
  source-dirs: src
  exposed-modules:
    - Text.Lexer
    - Text.Lexer.StateMachine
    - Text.Lexer.Parser
  ghc-options:
    - -Wall

executables:
  ParserStuff:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - ParserStuff

tests:
  ParserStuff-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - ParserStuff
